# Generated by Django 4.1.4 on 2022-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seller_email',
            field=models.CharField(default='seam@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
