# Generated by Django 4.1.4 on 2022-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='Groceries', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
